import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Saky Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.mainTitle + ' ' + styles.borderLine}>
          <h1>
            Hi there!
            <span className={styles.titleSpan}>
              I am Saqlain <b className={styles.mainTitleChunk}>Haider</b>
            </span>
            <span className={styles.titleSpan}>
              A Front End<b className={styles.mainTitleChunk}>Developer</b>
            </span>
          </h1>
          <button className={styles.button}>Follow me</button>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
